name: Compilar APK Android Nexus

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obter Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Configurar Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew

      - name: Compilar APK Universal
        run: ./gradlew assembleDebug --no-daemon

      - name: Disponibilizar Ficheiro APK
        uses: actions/upload-artifact@v4
        with:
          name: Syzygy-Nexus-Beta-ARM
          path: app/build/outputs/apk/debug/*.apk
